import { useState, useMemo } from 'react'
import { useApp } from '../../context/AppContext'
import Modal from '../../components/Modal'
import { QRCodeSVG } from 'qrcode.react'
import { loadImage } from '../../utils'
import { PAPER_SIZES } from '../../constants'
import { drawRealQROnCanvas } from '../../hooks/useComposer'
import {
  HiOutlineChartBar, HiOutlinePhotograph, HiOutlinePrinter, HiOutlineCalendar,
  HiOutlineDownload, HiOutlineTrash, HiOutlineEye, HiOutlineCloudUpload,
  HiOutlineCheckCircle, HiOutlineExclamationCircle, HiOutlineExternalLink,
} from 'react-icons/hi'

/**
 * Helper: resolve a session's photo to a displayable URL.
 * Handles data URLs, http URLs, local absolute paths, and relative paths.
 */
function resolveImageUrl(session) {
  // 0. Highest priority: QR-burned data URL generated by "Upload Ulang".
  //    A data URL changes its own string whenever the content changes, so
  //    using it avoids the browser image-cache problem that keeps showing
  //    the old (no-QR) photo after re-upload.
  if (session.qr_photo_data_url) return session.qr_photo_data_url

  // 1. Prefer file_path (saved by main process), then final_image_path
  let raw = session.file_path || session.final_image_path

  // 2. Fallback to photos field (old format or array of frames)
  if (!raw && session.photos) {
    if (Array.isArray(session.photos)) {
      const first = session.photos[0]
      raw = Array.isArray(first) ? first[0] : first
    } else if (typeof session.photos === 'string') {
      raw = session.photos
    }
    // photos can also be a number (photos.length) — skip in that case
  }

  // 3. Nothing usable
  if (!raw || typeof raw !== 'string') return null

  // 4. Already a displayable URL
  if (raw.startsWith('data:') || raw.startsWith('http') || raw.startsWith('blob:') || raw.startsWith('file://')) {
    return raw
  }

  // 5. Local filesystem path → file:/// protocol (3 slashes for Windows C:/...)
  const clean = raw.replace(/\\/g, '/')
  return clean.startsWith('/') ? `file://${clean}` : `file:///${clean}`
}

/**
 * Helper: ubah gambar sesi (path lokal / URL apapun) menjadi data URL base64
 * agar bisa dikirim ulang ke Google Drive.
 */
async function sessionImageToDataUrl(session, imageUrl, api) {
  const raw = session.file_path || session.final_image_path || imageUrl

  // Sudah berupa data URL
  if (raw && raw.startsWith('data:')) return raw

  // File lokal → minta main process membacanya (hanya tersedia di Electron)
  if (raw && !raw.startsWith('http') && api?.readFileAsDataUrl) {
    const result = await api.readFileAsDataUrl(raw)
    if (result?.success && result.dataUrl) return result.dataUrl
    throw new Error(result?.error || 'Gagal membaca file foto dari disk')
  }

  // Fallback: fetch URL (http/https/blob) lalu konversi ke base64
  if (imageUrl) {
    const res = await fetch(imageUrl)
    const blob = await res.blob()
    return await new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(reader.result)
      reader.onerror = reject
      reader.readAsDataURL(blob)
    })
  }

  throw new Error('Tidak ada file foto yang bisa diupload ulang')
}

/**
 * Helper: "bakar" (gambar) QR code langsung ke atas foto komposit.
 * Kalau template punya qr_slot, QR ditaruh sesuai posisi/ukuran template.
 * Kalau tidak, QR ditaruh default di pojok kanan-bawah foto.
 */
async function burnQrIntoImage(dataUrl, tpl, qrValue) {
  const img = await loadImage(dataUrl)
  const c = document.createElement('canvas')
  c.width = img.naturalWidth || img.width
  c.height = img.naturalHeight || img.height
  const ctx = c.getContext('2d')
  ctx.drawImage(img, 0, 0, c.width, c.height)

  if (tpl?.qr_slot) {
    const dims = PAPER_SIZES[tpl.paper_size] || [c.width, c.height]
    const multiplier = c.width / dims[0]
    const qr = tpl.qr_slot
    const qSize = qr.width ?? qr.size ?? 150
    const qx = qr.x ?? 50
    const qy = qr.y ?? 50
    await drawRealQROnCanvas(ctx, qrValue, qx, qy, qSize, multiplier)
  } else {
    // Default: pojok kanan-bawah, ~18% lebar foto
    const qSize = Math.round(c.width * 0.18)
    const margin = Math.round(c.width * 0.04)
    const qx = c.width - qSize - margin
    const qy = c.height - qSize - margin
    await drawRealQROnCanvas(ctx, qrValue, qx, qy, qSize, 1)
  }

  return c.toDataURL('image/jpeg', 0.92)
}

export default function AnalyticsPage() {
  const { sessions, events, templates, removeSession, editSession, uploadPhotoToDrive, updatePhotoToDrive, gdriveStatus, api } = useApp()
  const [filterEvent, setFilterEvent] = useState('all')
  const [previewSessionId, setPreviewSessionId] = useState(null)
  const previewSession = useMemo(
    () => (previewSessionId ? sessions.find(s => s.id === previewSessionId) || null : null),
    [previewSessionId, sessions]
  )
  const [reuploadingId, setReuploadingId] = useState(null)
  const [reuploadStep, setReuploadStep] = useState(null) // 'upload' | 'qr' | 'save'
  const [reuploadErrors, setReuploadErrors] = useState({})

  const REUPLOAD_STEPS = [
    { key: 'upload', label: 'Mengupload ke Google Drive...' },
    { key: 'qr', label: 'Menambahkan QR code ke foto...' },
    { key: 'save', label: 'Menyimpan hasil akhir...' },
  ]

  const handleReupload = async (session, imageUrl) => {
    setReuploadErrors(prev => ({ ...prev, [session.id]: null }))

    if (!gdriveStatus?.isAuthenticated) {
      setReuploadErrors(prev => ({ ...prev, [session.id]: 'Google Drive belum terhubung. Cek menu Settings.' }))
      return
    }

    const ev = events.find(e => e.id === session.event_id)
    if (!ev?.drive_folder_id) {
      setReuploadErrors(prev => ({ ...prev, [session.id]: 'Event ini belum punya folder Google Drive.' }))
      return
    }

    setReuploadingId(session.id)
    try {
      // 1. Ambil gambar ASLI (bersih, tanpa QR) sebagai data URL.
      //    Kalau sudah pernah upload ulang sebelumnya, pakai salinan asli yang
      //    sudah tersimpan supaya QR tidak menumpuk di atas QR lama.
      const originalDataUrl = session.original_photo_data_url
        || await sessionImageToDataUrl(session, imageUrl, api)
      const tpl = templates.find(t => t.id === session.template_id)
      const ext = (session.file_path || '').toLowerCase().endsWith('.gif') ? '.gif' : '.jpg'
      const filename = `reupload_${session.id}${ext}`

      // 2. Upload versi awal ke Drive supaya dapat link untuk QR
      setReuploadStep('upload')
      const uploadResult = await uploadPhotoToDrive(originalDataUrl, ev.drive_folder_id, filename)
      if (!uploadResult) {
        setReuploadErrors(prev => ({ ...prev, [session.id]: 'Upload ke Google Drive gagal. Coba lagi.' }))
        return
      }

      // 3. Gambar ulang foto dengan QR code tertanam, mengarah ke link Drive
      setReuploadStep('qr')
      const qrValue = uploadResult.downloadLink || uploadResult.viewLink
      let finalDataUrl = originalDataUrl
      let qrEmbedFailed = false
      try {
        finalDataUrl = await burnQrIntoImage(originalDataUrl, tpl, qrValue)
      } catch (err) {
        console.error('Gagal menambahkan QR ke foto:', err)
        qrEmbedFailed = true
      }

      // 4. Timpa file di Drive dengan versi ber-QR, lalu simpan lokal
      setReuploadStep('save')
      const updatedResult = await updatePhotoToDrive(finalDataUrl, uploadResult.id, filename)
      const driveResult = updatedResult || uploadResult

      let savedPath = session.file_path
      if (ev.folder_path && api?.savePhoto) {
        try {
          const localFilename = (session.file_path || '').split(/[\\/]/).pop() || filename
          const result = await api.savePhoto({
            folder: ev.folder_path,
            filename: localFilename,
            dataUrl: finalDataUrl,
            dpi: tpl?.dpi || 300,
          })
          savedPath = (typeof result === 'object' ? result.path : result) || savedPath
        } catch (err) {
          console.error('Gagal menyimpan ulang file lokal:', err)
        }
      }

      await editSession(session.id, {
        drive_file_id: driveResult?.id || session.drive_file_id,
        drive_view_link: driveResult?.viewLink || session.drive_view_link,
        drive_download_link: driveResult?.downloadLink || session.drive_download_link,
        file_path: savedPath,
        original_photo_data_url: originalDataUrl,
        qr_photo_data_url: finalDataUrl,
      })

      if (qrEmbedFailed) {
        setReuploadErrors(prev => ({ ...prev, [session.id]: 'Foto berhasil diupload, tapi QR gagal ditambahkan ke gambar. Coba upload ulang sekali lagi.' }))
      }
    } catch (err) {
      setReuploadErrors(prev => ({ ...prev, [session.id]: err.message || 'Upload ulang gagal.' }))
    } finally {
      setReuploadingId(null)
      setReuploadStep(null)
    }
  }

  // ── Stats ────────────────────────────────────────────────────────────────
  const stats = useMemo(() => {
    let filtered = sessions || []
    if (filterEvent !== 'all') {
      filtered = filtered.filter(s => s.event_id === filterEvent)
    }

    const today = new Date().toISOString().split('T')[0]
    const todaySessions = filtered.filter(s =>
      s.created_at && typeof s.created_at === 'string' && s.created_at.startsWith(today)
    )

    return {
      totalSessions: filtered.length,
      todaySessions: todaySessions.length,
      totalPrints: filtered.length,
      todayPrints: todaySessions.length,
    }
  }, [sessions, filterEvent])

  // ── Filtered & sorted sessions ───────────────────────────────────────────
  const filteredSessions = useMemo(() => {
    let filtered = sessions || []
    if (filterEvent !== 'all') {
      filtered = filtered.filter(s => s.event_id === filterEvent)
    }
    return [...filtered].sort((a, b) => new Date(b.created_at || 0) - new Date(a.created_at || 0))
  }, [sessions, filterEvent])

  // ── Stats card config ────────────────────────────────────────────────────
  const statCards = [
    { label: 'Total Sesi', value: stats.totalSessions, icon: HiOutlinePhotograph, color: '#D552A3', bg: 'rgba(213, 82, 163, 0.1)' },
    { label: 'Sesi Hari Ini', value: stats.todaySessions, icon: HiOutlineCalendar, color: '#4caf50', bg: 'rgba(76, 175, 80, 0.1)' },
    { label: 'Estimasi Kertas', value: `${stats.totalPrints} Lembar`, icon: HiOutlinePrinter, color: '#8b5cf6', bg: 'rgba(139, 92, 246, 0.1)' },
    { label: 'Kertas Hari Ini', value: `${stats.todayPrints} Lembar`, icon: HiOutlineChartBar, color: '#f0a030', bg: 'rgba(240, 160, 48, 0.1)' },
  ]

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>

      {/* ── Header Toolbar ───────────────────────────────────────────── */}
      <div className="toolbar" style={{ paddingRight: 120 }}>
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <span style={{ fontSize: 16, fontWeight: 700 }}>Data & Analytics</span>
          <span style={{ fontSize: 11, color: 'var(--color-text-muted)' }}>
            Tinjau statistik pencetakan dan galeri foto event
          </span>
        </div>
        <div className="toolbar-spacer" />
        <select
          className="select"
          style={{ width: 200, padding: '6px 24px 6px 12px', fontSize: 13, height: 32 }}
          value={filterEvent}
          onChange={(e) => setFilterEvent(e.target.value)}
        >
          <option value="all">Semua Event</option>
          {events.map(ev => (
            <option key={ev.id} value={ev.id}>{ev.name}</option>
          ))}
        </select>
      </div>

      {/* ── Body ─────────────────────────────────────────────────────── */}
      <div className="app-body" style={{ padding: 24, animation: 'fadeIn 0.3s' }}>

        {/* Stats Cards */}
        <div className="grid grid-cols-4 gap-5 mb-8">
          {statCards.map((item, i) => {
            const Icon = item.icon
            return (
              <div key={i} className="card p-5 flex items-center gap-4 transition-transform hover:scale-[1.02] cursor-default">
                <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0" style={{ background: item.bg, color: item.color }}>
                  <Icon size={26} />
                </div>
                <div className="flex flex-col overflow-hidden">
                  <span className="text-[10px] font-bold text-[var(--color-text-muted)] uppercase tracking-[0.1em] mb-0.5">{item.label}</span>
                  <span className="text-xl font-black truncate">{item.value}</span>
                </div>
              </div>
            )
          })}
        </div>

        {/* Gallery */}
        <h2 className="text-lg font-bold mb-4">Galeri Sesi Terbaru</h2>
        <div className="flex-1 overflow-y-auto pr-2 pb-4">
          {filteredSessions.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-40 text-[var(--color-text-muted)] border-2 border-dashed border-[var(--color-border)] rounded-lg">
              <HiOutlinePhotograph size={40} className="mb-2 opacity-50" />
              <p>Belum ada foto yang diambil</p>
            </div>
          ) : (
            <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-4">
              {filteredSessions.map(session => {
                const ev = events.find(e => e.id === session.event_id)
                const tpl = templates.find(t => t.id === session.template_id)
                const imageUrl = resolveImageUrl(session)

                const isUploaded = !!session.drive_view_link
                const isReuploading = reuploadingId === session.id
                const reuploadError = reuploadErrors[session.id]

                return (
                  <div key={session.id} className="card p-3 flex flex-col group relative overflow-hidden transition-all hover:border-[var(--color-accent)]">
                    <div className="aspect-[2/3] w-full bg-[var(--color-bg-base)] rounded-lg flex items-center justify-center mb-3 overflow-hidden border border-[var(--color-border-subtle)] relative">
                      {imageUrl ? (
                        <img src={imageUrl} className="w-full h-full object-cover" alt="Session" loading="lazy" />
                      ) : (
                        <div className="flex flex-col items-center opacity-30">
                          <HiOutlinePhotograph size={32} />
                          <div className="text-[10px] mt-1">No Image</div>
                        </div>
                      )}

                      {/* Upload status badge */}
                      <div
                        title={isUploaded ? 'Sudah terupload ke Google Drive' : 'Belum terupload ke Google Drive'}
                        style={{
                          position: 'absolute', top: 6, right: 6, width: 22, height: 22, borderRadius: '50%',
                          display: 'flex', alignItems: 'center', justifyContent: 'center',
                          background: isUploaded ? 'rgba(76,175,80,0.9)' : 'rgba(0,0,0,0.55)',
                          color: '#fff',
                        }}
                      >
                        {isUploaded ? <HiOutlineCheckCircle size={14} /> : <HiOutlineExclamationCircle size={14} />}
                      </div>

                      {/* Loading overlay saat upload ulang berlangsung */}
                      {isReuploading ? (
                        <div className="absolute inset-0 bg-black/75 flex flex-col items-center justify-center gap-2 px-3 text-center">
                          <div style={{ width: 22, height: 22, borderRadius: '50%', border: '2px solid rgba(255,255,255,0.25)', borderTopColor: '#D552A3', animation: 'spin 0.7s linear infinite' }} />
                          <span style={{ fontSize: 11, color: 'white', fontWeight: 600 }}>
                            {REUPLOAD_STEPS.find(s => s.key === reuploadStep)?.label || 'Memproses...'}
                          </span>
                        </div>
                      ) : (
                      /* Hover Actions */
                      <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col items-center justify-center gap-2">
                        {imageUrl && (
                          <button className="btn btn-sm w-28" onClick={() => setPreviewSessionId(session.id)}>
                            <HiOutlineEye /> Preview
                          </button>
                        )}
                        {imageUrl && (
                          <button className="btn btn-launch btn-sm w-28" onClick={() => {
                            const a = document.createElement('a')
                            a.href = imageUrl
                            a.download = `photo_${session.id}.jpg`
                            a.click()
                          }}>
                            <HiOutlineDownload /> Unduh
                          </button>
                        )}
                        <button className="btn btn-danger btn-sm w-28" onClick={() => {
                          if (confirm('Hapus sesi ini secara permanen?')) {
                            removeSession(session.id)
                          }
                        }}>
                          <HiOutlineTrash /> Hapus
                        </button>
                      </div>
                      )}
                    </div>

                    <div className="text-sm font-bold truncate mb-1">{ev?.name || 'Unknown Event'}</div>
                    <div className="text-xs text-[var(--color-text-muted)] truncate">{tpl?.name || 'Unknown Template'}</div>
                    <div className="text-xs text-[var(--color-text-muted)] mt-2 opacity-80">
                      {session.created_at ? new Date(session.created_at).toLocaleString('id-ID') : 'Unknown Time'}
                    </div>
                    {reuploadError && (
                      <div className="text-[10px] mt-1" style={{ color: 'var(--color-danger)' }}>
                        {reuploadError}
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          )}
        </div>
      </div>

      {/* ── Preview Modal ────────────────────────────────────────────── */}
      <Modal
        isOpen={!!previewSession}
        onClose={() => setPreviewSessionId(null)}
        title="Preview Foto"
        footer={previewSession && (
          <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end', width: '100%' }}>
            {previewSession.drive_view_link && (
              <a
                className="btn btn-sm"
                href={previewSession.drive_view_link}
                target="_blank"
                rel="noreferrer"
              >
                <HiOutlineExternalLink /> Buka di Drive
              </a>
            )}
            <button
              className="btn btn-primary btn-sm"
              onClick={() => handleReupload(previewSession, resolveImageUrl(previewSession))}
              disabled={reuploadingId === previewSession.id}
            >
              <HiOutlineCloudUpload /> {reuploadingId === previewSession.id ? 'Memproses...' : (previewSession.drive_view_link ? 'Upload Ulang' : 'Upload ke Drive')}
            </button>
            <button className="btn btn-sm btn-ghost" onClick={() => setPreviewSessionId(null)}>Tutup</button>
          </div>
        )}
      >
        {previewSession && (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12 }}>
            {reuploadingId === previewSession.id ? (
              /* ── Loading screen saat upload ulang + burn QR ke foto ── */
              <div style={{ width: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 24, padding: '24px 8px' }}>
                <div style={{
                  width: 56, height: 56, borderRadius: 14,
                  background: 'linear-gradient(135deg, #462C7D, #D552A3)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  boxShadow: '0 0 30px rgba(213,82,163,0.4)',
                  animation: 'pulse 1.5s ease-in-out infinite',
                }}>
                  <HiOutlineCloudUpload size={26} color="white" />
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 12, width: '100%', maxWidth: 300 }}>
                  {REUPLOAD_STEPS.map((s, i) => {
                    const currentIdx = REUPLOAD_STEPS.findIndex(x => x.key === reuploadStep)
                    const done = i < currentIdx
                    const active = i === currentIdx
                    return (
                      <div key={s.key} style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                        <div style={{
                          width: 24, height: 24, borderRadius: '50%', flexShrink: 0,
                          background: done ? '#4ade80' : active ? '#D552A3' : 'var(--color-border-subtle)',
                          display: 'flex', alignItems: 'center', justifyContent: 'center',
                        }}>
                          {done ? (
                            <HiOutlineCheckCircle size={13} color="white" />
                          ) : active ? (
                            <div style={{ width: 9, height: 9, borderRadius: '50%', border: '2px solid rgba(255,255,255,0.4)', borderTopColor: 'white', animation: 'spin 0.7s linear infinite' }} />
                          ) : null}
                        </div>
                        <span style={{ fontSize: 12, fontWeight: active ? 700 : 500, color: done ? '#4ade80' : active ? 'var(--color-text)' : 'var(--color-text-muted)' }}>
                          {s.label}
                        </span>
                      </div>
                    )
                  })}
                </div>
                <style>{`@keyframes pulse { 0%,100% { box-shadow: 0 0 30px rgba(213,82,163,0.4); } 50% { box-shadow: 0 0 45px rgba(213,82,163,0.7), 0 0 15px rgba(70,44,125,0.5); } }`}</style>
              </div>
            ) : (
              <>
                {resolveImageUrl(previewSession) ? (
                  <img
                    src={resolveImageUrl(previewSession)}
                    alt="Preview sesi"
                    style={{ maxWidth: '100%', maxHeight: '65vh', borderRadius: 8, border: '1px solid var(--color-border-subtle)' }}
                  />
                ) : (
                  <div className="flex flex-col items-center opacity-50 py-10">
                    <HiOutlinePhotograph size={40} />
                    <div className="text-xs mt-2">Tidak ada gambar</div>
                  </div>
                )}

                {/* QR Code — sudah ditempel langsung di foto setelah upload ulang */}
                {(previewSession.drive_download_link || previewSession.drive_view_link) && (
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ background: 'white', borderRadius: 12, padding: 16, display: 'inline-block' }}>
                      <QRCodeSVG
                        value={previewSession.drive_download_link || previewSession.drive_view_link}
                        size={140}
                        bgColor="white"
                        fgColor="#1a1425"
                        level="M"
                      />
                    </div>
                    <p style={{ fontSize: 11, color: 'var(--color-text-muted)', marginTop: 8 }}>
                      QR ini juga sudah ditempel langsung di foto. Scan untuk membuka / mengunduh dari Google Drive.
                    </p>
                  </div>
                )}
              </>
            )}

            <div style={{ width: '100%', fontSize: 12, color: 'var(--color-text-muted)', display: 'flex', flexDirection: 'column', gap: 4 }}>
              <div><strong style={{ color: 'var(--color-text)' }}>Event:</strong> {events.find(e => e.id === previewSession.event_id)?.name || 'Unknown Event'}</div>
              <div><strong style={{ color: 'var(--color-text)' }}>Template:</strong> {templates.find(t => t.id === previewSession.template_id)?.name || 'Unknown Template'}</div>
              <div><strong style={{ color: 'var(--color-text)' }}>Waktu:</strong> {previewSession.created_at ? new Date(previewSession.created_at).toLocaleString('id-ID') : 'Unknown Time'}</div>
              <div>
                <strong style={{ color: 'var(--color-text)' }}>Status Upload:</strong>{' '}
                {previewSession.drive_view_link ? (
                  <span style={{ color: '#4caf50' }}>Sudah diupload ke Google Drive</span>
                ) : (
                  <span style={{ color: 'var(--color-danger)' }}>Belum diupload ke Google Drive</span>
                )}
              </div>
              {reuploadErrors[previewSession.id] && (
                <div style={{ color: 'var(--color-danger)' }}>{reuploadErrors[previewSession.id]}</div>
              )}
            </div>
          </div>
        )}
      </Modal>
    </div>
  )
}
